version: "3.8"

services:
  web:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5555:5555"
      - "7070:7070"
    environment:
      - PORT=5000
    depends_on:
      - postgesql
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

  redis:
    image: redis:7.0-alpine
    container_name: api_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_api

  postgesql:
    image: postgres:12-alpine
    container_name: api_postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web_api